version: "3.9"

services:
  backend:
    image: ghcr.io/behrouzrajaei/conduit-backend:${VERSION}
    container_name: conduit-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: ghcr.io/behrouzrajaei/conduit-frontend:${VERSION}
    container_name: conduit-frontend
    env_file:
      - .env
    ports:
      - "8282:80"
    depends_on:
      - backend

  db:
    image: postgres:9.6
    container_name: conduit-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
