services:
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: http://backend:8000/api
    container_name: conduit-frontend
    restart: unless-stopped
    ports:
      - "8282:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: conduit-backend
    command: ["sh", "/app/entrypoint.sh"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:9.6
    container_name: conduit-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - conduit_postgres_data:/var/lib/postgresql/data

volumes:
  conduit_postgres_data:
